port: 8983
collection:
  dir: solr/config/
  name: development
  persist: false
configsets:
  - dir: solr/config/
name: homosaurus-development
version: 8.11.2
verbose: true
download_dir: solr/binary/
instance_dir: solr/instance/
ignore_checksum: true
#solr_options:
#  force: true
